apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meetups.kube.tokyo
spec:
  # metadata.nameの後方に一致
  group: kube.tokyo
  version: v1
  scope: Namespaced
  names:
    # リソースの複数形の名前
    plural: meetups
    # 単数形の名前, URLのpathに使われる
    singular: meetup
    kind: Meetup
    # kubectlのgetで使える省略名
    shortNames:
      - mp
